apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  name: default
  namespace: openshift-ingress-operator
spec:
  replicas: 2
#  routeSelector:
#    matchLabels:
#      type: public
#  namespaceSelector:
#    matchLabels:
#      environment: dmz
